# Question 1 

Module v/s Library

## Module

Modules in Python are simply Python files with a .py extension
The name of the module will be the name of the file. A Python module can have a set of functions, classes or variables defined and implemented. 
There are actually three different ways to define a module in Python:

   * A module can be written in Python itself.
   * A module can be written in C and loaded dynamically at run-time, like the re (regular expression) module.
   * A built-in module is intrinsically contained in the interpreter, like the itertools module.

A module’s contents are accessed the same way in all three cases: with the import statement.

Here, the focus will mostly be on modules that are written in Python. The cool thing about modules written in Python is that they are exceedingly straightforward to build. All you need to do is create a file that contains legitimate Python code and then give the file a name with a .py extension. That’s it! No special syntax or voodoo is necessary.

For example, In the example above, we will have two files, we will have:

In [39]:
# A simple module, calc.py 
def add(x, y): 
    return (x+y) 
  
def subtract(x, y): 
    return (x-y) 


### The import statement
We can use any Python source file as a module by executing an import statement in some other Python source file.
When interpreter encounters an import statement, it imports the module if the module is present in the search path. A search path is a list of directories that the interpreter searches for importing a module. For example, to import the module calc.py, we need to put the following command at the top of the script :

In [ ]:
# importing  module calc.py 
import calc 
  
print add(10, 2) 



### The from import Statement

Python’s from statement lets you import specific attributes from a module. The from .. import .. has the following syntax :

In [ ]:
# importing sqrt() and factorial from the  
# module math 
from math import sqrt, factorial 
  
# if we simply do "import math", then 
# math.sqrt(16) and math.factorial() 
# are required. 
print sqrt(16) 
print factorial(6) 


## Libraries

Python library is a collection of functions and methods that allows you to perform many actions without writing your code. For example, the Python imaging library (PIL). is one of the core libraries for image manipulation in Python. Pillow is an actively developed fork of PIL. Open-CV Python is a library of Python aimed at real-time computer vision and image processing. It makes use of Numpy, another library for numerical operations.

Each library in Python contains a huge number of useful modules that you can import for your every day programming.


## Question 2: 
How to make a matrix which has each of its elements as 2?

In [41]:
import numpy as np
x= 2* np.ones((7,7))
x

array([[2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2.]])

## Question 3: 
Suppose we have an array -- [0.26,0.34,0.49] how can this array be converted into --[5.26,5.34,5.49]

In [44]:
number = np.random.rand(3)
five_num = [5,5,5]
final=np.array(five_num)

number+ five_num




array([5.11626704, 5.17595352, 5.92027208])

## Question 4: 

Explain functionality of the following:

### 1) TILE  : 
About :

numpy.tile(arr, reps) : constructs a new array by repeating array – ‘arr’, the number of times we want to 
repeat as per repetitions. The resulted array will have dimensions max(arr.ndim, repetitions) where, repetitions is
the length of repetitions.
        
         If arr.ndim > repetitions, reps is promoted to arr.ndim by pre-pending 1’s to it.
         If arr.ndim < repetitions, reps is promoted to arr.ndim by pre-pending new axis.

### array       : [array_like]Input array. 
### repetitions : No. of repetitions of arr along each axis. 

In [47]:
repeat_array = np.array([1,2,3,4])
np.tile(repeat_array, 10)



array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2,
       3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

### 2) DIAG :
Extract a diagonal or construct a diagonal array.

#### Parameters:	

v : array_like

    If v is a 2-D array, return a copy of its k-th diagonal. If v is a 1-D array, return a 2-D array with v on the k-th    diagonal.

k : int, optional

    Diagonal in question. The default is 0. Use k>0 for diagonals above the main diagonal, and k<0 for diagonals below the main diagonal.

#### Returns:	

out : ndarray

    The extracted diagonal or constructed diagonal array.


In [48]:
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
np.diag(x)

array([0, 4, 8])

In [50]:
np.diag(x, k=1)

array([1, 5])

In [51]:
np.diag(x, k=-1)

array([3, 7])

In [52]:
np.diag(np.diag(x))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

In [56]:
array_1=[11,22,33,44,55,66,77,88,99,100]

In [57]:
np.diag(array_1)

array([[ 11,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,  22,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,  33,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,  44,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,  55,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,  66,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,  77,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  88,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  99,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 100]])

### 3) INVERSE

Inverse of a matrix is computed from scipy.linalg.inv() function.


#### Parameters:	

a : (…, M, M) array_like

    Matrix to be inverted.

#### Returns:	

ainv : (…, M, M) ndarray or matrix

    (Multiplicative) inverse of the matrix a.

#### Raises:	

LinAlgError

    If a is not square or inversion fails.


In [64]:
from numpy.linalg import inv
a = np.array([[1, 0], [2, 1]])
a

array([[1, 0],
       [2, 1]])

In [65]:
inv(a)

array([[ 1.,  0.],
       [-2.,  1.]])

### 4) TRANSPOSE
Returns a view of the array with axes transposed.

#### Parameters:	

###### axes : None, tuple of ints, or n ints

        None or no argument: reverses the order of the axes.
        tuple of ints: i in the j-th place in the tuple means a‘s i-th axis becomes a.transpose()‘s j-th axis.
        n ints: same as an n-tuple of the same ints (this form is intended simply as a “convenience” alternative to the tuple form)

#### Returns:	

###### out : ndarray

    View of a, with axes suitably permuted.


In [67]:
a = np.array([[1, 2], [3, 4]])

In [68]:
a

array([[1, 2],
       [3, 4]])

In [69]:
 a.transpose()

array([[1, 3],
       [2, 4]])

### Question 4: Why everything in Python is an object?

* In Python, pretty much everything is an object, whether it is a number, a function… or even None.
* Python is using a pure object model where classes are instances of a meta-class “type” (in Python, the terms “type” and “class” are synonyms). And “type” is the only class which is an instance of itself
* This object model can be useful when we want information about a particular resource in Python. Except for the Python keywords (e.g. if, def, globals), using “type(<name>)” or “dir(<name>)” -or just type the resource name and press enter- will work on pretty much anything.
        

### Question 5: Functionality of np.newaxis

he newaxis expression is used to increase the dimension of the existing array by one more dimension, when used once. Thus,

    * 1D array will become 2D array
    * 2D array will become 3D array
    * 3D array will become 4D array

and so on. 

In [70]:
# 1D array
arr = np.arange(4)
arr.shape

(4,)

In [71]:
# make it as row vector by inserting an axis along first dimension
row_vec = arr[np.newaxis, :]
row_vec.shape



(1, 4)

In [72]:
# make it as column vector by inserting an axis along second dimension
col_vec = arr[:, np.newaxis]
col_vec.shape


(4, 1)